spring.application.name=screenmatch
openai.api.key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost/alura_series
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
